class LocalizationData {
  static const Map<String, String> english = {
    'app_title': 'BookMyEvent',
    'greeting': 'Hi, Fahad & Ayesha',
    'wedding_in': 'WEDDING IN',
    'days': 'DAYS',
    'hours': 'HOURS',
    'mins': 'MINS',
    'planning_tools': 'PLANNING TOOLS',
    'latest_updates': 'LATEST UPDATES',
    'see_all': 'SEE ALL',
    'budget_ai': 'Budget AI',
    'guests': 'Guests',
    'social_feed': 'Social Feed',
    'seating': 'Seating',
    'wallet': 'Wallet',
    'vendor_bids': 'Vendor Bids',
    'gifts': 'Gifts',
    'check_in': 'Check-In',
    'guide': 'Guide',
    'daftar': 'Daftar',
    'rasala_title': 'Cultural Rasala',
    'smart_alerts': 'Smart Alerts',
    'language_toggle': 'اردو',
    'about_ceremony': 'About the Ceremony',
    'key_traditions': 'Key Traditions',
    'dos': 'Do\'s',
    'donts': 'Don\'ts',
    'significance': 'Significance',
    'marketplace': 'Marketplace',
    'smart_match': 'AI Smart Match',
    'post_requirement': 'Post Requirement',
    'best_value': 'Best Value',
    'starts_from': 'Starts from',
    'vendors': 'Vendors',
    'budget_predictor': 'AI Budget Predictor',
    'planning_details': 'Planning Details',
    'guest_count': 'Guest Count',
    'city': 'City',
    'target_budget': 'Target Budget',
    'generate_forecast': 'Generate Smart Forecast',
    'prediction_result': 'AI Prediction Result',
    'market_intelligence': 'Market Intelligence',
    'category_breakdown': 'Category Breakdown',
    'social_title': 'Event Feed',
    'live_mode': 'Live Mode',
    'share_memory': 'Share a Memory',
    'upload_photos': 'Upload Photos',
    'post_to_feed': 'Post to Event Feed',
    'stories': 'Memories',
    'your_story': 'Add Memory',
    'wallet_title': 'Wedding Wallet',
    'total_paid': 'Total Paid',
    'pending': 'Pending',
    'budget_progress': 'Budget Progress',
    'vendor_milestones': 'Vendor Milestones',
    'recent_transactions': 'Recent Activity',
    'pay_now': 'Pay Now',
    'rsvp_title': 'RSVP Dashboard',
    'confirmed': 'Confirmed',
    'declined': 'Declined',
    'distribution': 'RSVP Distribution',
    'recent_responses': 'Recent Responses',
    'not_sent': 'Not Sent',
    'seating_title': 'Seating Planner',
    'unseated_guests': 'Unseated Guests',
    'all_sections': 'All Sections',
    'seats': 'Seats',
    'stage': 'ROYAL STAGE',
    'assigned_success': 'Assigned to table',
    'search_vendors': 'Search vendors...',
    'all_vendors': 'All Vendors',
    'my_requests': 'My Requests',
    'guest_list_title': 'Royal Guest List',
    'families': 'Families',
    'no_guests_found': 'No guests found',
    'add_guest': 'Add Guest',
    'all': 'All',
    'bride_side': 'Bride Side',
    'groom_side': 'Groom Side',
    'login_tagline': 'Your Dream Wedding, Perfectly Planned',
    'welcome_back': 'Welcome Back',
    'verify_number': 'Verify Number',
    'otp_sent_to': 'Code sent to',
    'login_subtitle': 'Plan your wedding like a pro',
    'resend_code': 'Resend Code',
    'by_continuing': 'By continuing, you agree to our',
    'terms': 'Terms',
    'privacy': 'Privacy Policy',
  };

  static const Map<String, String> urdu = {
    'app_title': 'بُک مائی ایونٹ',
    'greeting': 'سلام، فہد اور عائشہ',
    'wedding_in': 'شادی میں باقی ہیں',
    'days': 'دن',
    'hours': 'گھنٹے',
    'mins': 'منٹ',
    'planning_tools': 'منصوبہ بندی کے آلات',
    'latest_updates': 'تازہ ترین اپ ڈیٹس',
    'see_all': 'سب دیکھیں',
    'budget_ai': 'بجٹ اے آئی',
    'guests': 'مہمان',
    'social_feed': 'سوشل فیڈ',
    'seating': 'نشستیں',
    'wallet': 'بٹوا',
    'vendor_bids': 'وینڈر بولیاں',
    'gifts': 'تحائف',
    'check_in': 'چیک ان',
    'guide': 'رہنما',
    'daftar': 'دفتر',
    'rasala_title': 'ثقافتی رسالہ',
    'smart_alerts': 'سمارٹ الرٹس',
    'language_toggle': 'English',
    'about_ceremony': 'تقریب کے بارے میں',
    'key_traditions': 'اہم روایات',
    'dos': 'کیا کرنا ہے',
    'donts': 'کیا نہیں کرنا',
    'significance': 'اہمیت',
    'marketplace': 'مارکیٹ پلیس',
    'smart_match': 'اے آئی اسمارٹ میچ',
    'post_requirement': 'ضرورت بتائیں',
    'best_value': 'بہترین انتخاب',
    'starts_from': 'سے شروع',
    'vendors': 'وینڈرز',
    'budget_predictor': 'اے آئی بجٹ پرڈیکٹر',
    'planning_details': 'منصوبہ بندی کی تفصیلات',
    'guest_count': 'مہمانوں کی تعداد',
    'city': 'شہر',
    'target_budget': 'ٹارگٹ بجٹ',
    'generate_forecast': 'سمارٹ فورکاسٹ بنائیں',
    'prediction_result': 'اے آئی پیشگوئی کا نتیجہ',
    'market_intelligence': 'مارکیٹ کی معلومات',
    'category_breakdown': 'زمرہ جات کی تفصیل',
    'social_title': 'ایونٹ فیڈ',
    'live_mode': 'لائیو موڈ',
    'share_memory': 'یادیں شیئر کریں',
    'upload_photos': 'تصاویر اپ لوڈ کریں',
    'post_to_feed': 'فیڈ میں پوسٹ کریں',
    'stories': 'یادیں',
    'your_story': 'یاد شامل کریں',
    'wallet_title': 'ویڈنگ والٹ',
    'total_paid': 'کل ادائیگی',
    'pending': 'باقی رقم',
    'budget_progress': 'بجٹ کی صورتحال',
    'vendor_milestones': 'وینڈر کی قسطیں',
    'recent_transactions': 'حالیہ تفصیلات',
    'pay_now': 'ادائیگی کریں',
    'rsvp_title': 'آر ایس وی پی ڈیش بورڈ',
    'confirmed': 'تصدیق شدہ',
    'declined': 'معذرت',
    'distribution': 'آر ایس وی پی کی صورتحال',
    'recent_responses': 'حالیہ جوابات',
    'not_sent': 'نہیں بھیجا',
    'seating_title': 'سیٹنگ پلانر',
    'unseated_guests': 'غیر نشست مہمان',
    'all_sections': 'تمام حصے',
    'seats': 'نشستیں',
    'stage': 'شاہی اسٹیج',
    'assigned_success': 'ٹیبل پر منتقل کر دیا گیا',
    'search_vendors': 'وینڈر تلاش کریں...',
    'all_vendors': 'تمام وینڈرز',
    'my_requests': 'میری درخواستیں',
    'guest_list_title': 'شاہی مہمانوں کی فہرست',
    'families': 'خاندان',
    'no_guests_found': 'کوئی مہمان نہیں ملا',
    'add_guest': 'مہمان شامل کریں',
    'all': 'تمام',
    'bride_side': 'دلہن کی طرف',
    'groom_side': 'دولہا کی طرف',
    'login_tagline': 'آپ کی خوابوں کی شادی، بہترین منصوبہ بندی',
    'welcome_back': 'خوش آمدید',
    'verify_number': 'نمبر کی تصدیق کریں',
    'otp_sent_to': 'کوڈ بھیجا گیا',
    'login_subtitle': 'پیشہ ورانہ انداز میں شادی کی منصوبہ بندی کریں',
    'resend_code': 'دوبارہ کوڈ بھیجیں',
    'by_continuing': 'جاری رکھ کر، آپ ہماری شرائط سے اتفاق کرتے ہیں',
    'terms': 'شرائط',
    'privacy': 'رازداری کی پالیسی',
  };
}
